# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 13.39.16.113
  become: yes

  tasks:

- name: Call Roles
  hosts: 13.39.16.113
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
