---
- hosts: all
  become: yes

  pre_tasks:
    - name: "Install podman"
      ansible.builtin.apt:
        name:
          - podman
        state: present

    - file: 
        group: ubuntu
        mode: 488
        owner: ubuntu
        path: /home/ubuntu/postgres
        state: directory
      name: "creating directory"
    
    - name: "Copy dockerfile"
      synchronize:
          dest: /home/ubuntu/postgres/Dockerfile
          mode: push
          src: Dockerfile
      delegate_to: localhost
    
    - name: "Build postgres image"
      containers.podman.podman_image:
        name: postgres
        path: /home/ubuntu/postgres/

    - name: Run container
      containers.podman.podman_container:
        name: postgres-container
        image: docker.io/postgres
        env:
          POSTGRES_PASSWORD: 1234 
          POSTGRES_DB: test
        state: started

