--- 
become: true
hosts: all
pre_tasks: 
  - 
    ansible.builtin.apt: 
      name: 
        - podman
      state: present
    name: "Install podman"
  - 
    delegate_to: localhost
    name: "Copy dockerfile"
    synchronize: 
      dest: /home/ubuntu/postgres/Dockerfile
      mode: push
      src: Dockerfile
