--- 
- 
  hosts: all
  name: "Run python scripts in remote machine"
  tasks: 
    - 
      file: 
        group: ubuntu
        mode: 488
        owner: ubuntu
        path: /home/ubuntu/test_python
        state: directory
      name: "creating directory"
    - 
      name: "copy python scripts"
      synchronize:
        dest: /home/ubuntu/test_python/test_python.py
        mode: push
        src: test_python.py
      delegate_to: localhost
    - 
      command: "python /home/ubuntu/test_python/test_python.py"
      name: "run test_python.py"
    - 
      command: "cat /home/ubuntu/test_python"
      name: "read file content"
      register: out
    - 
      debug: 
        msg: "{{ out.stdout }}"
      name: "Print the msg"
